version: 1.0
provider:
  name: openfaas
  gateway: https://faas.arkaangel.com
#  gateway: http://faas.fairu.local
functions:
  faas-pdf2zip:
    lang: dockerfile
    handler: ./faas-pdf2zip
    image: faas-pdf2zip:latest

